/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import clases.conectar;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;



public class formulario extends javax.swing.JFrame {
    conectar conecto;
    
    PreparedStatement ps;
    ResultSet rs;
    
    private static Connection conn;
    private static final String driver = "com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "";
    private static final String url = "jdbc:mysql://localhost:3306/juzgado";
    
    public formulario(){
        initComponents();
    }
    
    public Connection getConnection(){
        Connection conn=null;
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(url, user, pass);
            if(conn !=null) {
                System.out.println("La conexion se establecio bien con la DB");
            }
            
        } catch (ClassNotFoundException | SQLException e ) {
            System.out.println("Error al conectar con la DB" + e);
        }
        return conn;
    }
    
    public void Desconectar (){
        conn=null;
        if (conn == null) {
            System.out.println("Se desconecto la Db");
           
        }
    }    
    
    public void borrarCajas (){
        cajanombre.setText(null);
        cajacedula.setText(null);
        cajamotivovisita.setText(null);
        cajaocupacion.setText(null);
        
        
    }

    /**
     * Creates new form formulario
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cajanombre = new javax.swing.JTextField();
        cajacedula = new javax.swing.JTextField();
        cajamotivovisita = new javax.swing.JTextField();
        cajaocupacion = new javax.swing.JTextField();
        bconectar = new javax.swing.JButton();
        bdesconectar = new javax.swing.JButton();
        benviar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 110, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Cedula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 80, 20));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Motivo Visita:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 140, 20));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Ocupacion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 110, 20));

        cajanombre.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(cajanombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 210, -1));

        cajacedula.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(cajacedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 230, -1));

        cajamotivovisita.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(cajamotivovisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 170, -1));

        cajaocupacion.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(cajaocupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 190, -1));

        bconectar.setBackground(new java.awt.Color(255, 255, 255));
        bconectar.setText("Conectar");
        bconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconectarActionPerformed(evt);
            }
        });
        getContentPane().add(bconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        bdesconectar.setBackground(new java.awt.Color(255, 255, 255));
        bdesconectar.setText("Desconectar");
        bdesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(bdesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        benviar.setBackground(new java.awt.Color(255, 255, 255));
        benviar.setText("Enviar");
        benviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benviarActionPerformed(evt);
            }
        });
        getContentPane().add(benviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/juzfa_preview_rev_1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 170, 170));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("JUZGADO VICTOR ROJAS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 310, 70));

        jfondo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1457005317_021243_1457005573_noticia_normal.jpg"))); // NOI18N
        getContentPane().add(jfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconectarActionPerformed
        conecto = new conectar();
        Connection reg = conecto.getConnection();
    }//GEN-LAST:event_bconectarActionPerformed

    private void bdesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdesconectarActionPerformed
        conecto.Desconectar();
    }//GEN-LAST:event_bdesconectarActionPerformed

    private void benviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benviarActionPerformed
        Connection conn = null;
        
        try {
            conn = getConnection();
            ps = conn.prepareStatement("INSERT INTO datos (nombre, cedula, motivovisita, ocupacion ,fechareg) VALUES(?,?,?,?,?)");
            ps.setString(1, cajanombre.getText());
            ps.setString(2, cajacedula.getText());
            ps.setString(3, cajamotivovisita.getText());
            ps.setString(4, cajaocupacion.getText());
            ps.setDate(5, Date.valueOf(LocalDate.now()));
            
            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Los datos fueron enviados correctamente");
                borrarCajas();
            }else{
                JOptionPane.showMessageDialog(null, "Los datos no fueron enviados");
            }
            conn.close();
            
            
        } catch (Exception e){
            System.out.println(e);
            
        }
    }//GEN-LAST:event_benviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bconectar;
    private javax.swing.JButton bdesconectar;
    private javax.swing.JButton benviar;
    private javax.swing.JTextField cajacedula;
    private javax.swing.JTextField cajamotivovisita;
    private javax.swing.JTextField cajanombre;
    private javax.swing.JTextField cajaocupacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jfondo;
    // End of variables declaration//GEN-END:variables
}
